<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <ApplicationIcon>..\..\assets\icons\favicon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia.Desktop" Version="12.0.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\\SpineViewer.App\\SpineViewer.App.csproj" GlobalPropertiesToRemove="NuGetInteractive" />
  </ItemGroup>
</Project>
